version: 0.2

phases:
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
      - yarn cypress-ci
  post_build:
    commands:
      - echo Build completed on `date`
    